on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "Makefile"
      - ".github/workflows/nightly-build.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "Makefile"
      - ".github/workflows/nightly-build.yml"
name: nightly-build
jobs:
  build:
    # strategy:
    #   fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24.5

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make V=1 release -j$(nproc)
